tmp_path = "/tmp/tiflash/data/tiflash/tmp"
display_name = "TiFlash"
default_profile = "default"
users_config = "config/tiflash-users.toml"
path = "/tmp/tiflash/data/tiflash/db"
mark_cache_size = 5368709120
listen_host = "0.0.0.0"
tcp_port = 9000
http_port = 8123
interserver_http_port = 9009
[flash]
	tidb_status_addr = "tidb0:10080"
	service_addr = "tiflash0:3930"
	[flash.flash_cluster]
		refresh_interval = 20
		update_rule_interval = 5
		master_ttl = 60
		cluster_manager_path = "../tiflash/flash_cluster_manager"
	[flash.proxy]
    addr = "0.0.0.0:20170"
    advertise-addr = "tiflash0:20170"
    data-dir = "/tmp/tiflash/data/tikv-learner"
    config = "config/tikv-learner.toml"
    log-file = "/tmp/tiflash/log/tikv-learner.log"
[logger]
	count = 10
	errorlog = "/tmp/tiflash/log/tiflash-error.log"
	size = "1000M"
	log = "/tmp/tiflash/log/tiflash.log"
	level = "trace"
[application]
	runAsDaemon = true

[raft]
	pd_addr = "pd0:2379"
