# TiKV config template
#  Human-readable big numbers:
#   File size(based on byte): KB, MB, GB, TB, PB
#    e.g.: 1_048_576 = "1MB"
#   Time(based on ms): ms, s, m, h
#    e.g.: 78_000 = "1.3m"

log-file="./log/tikv0/tikv.log"

[readpool.storage]

[readpool.coprocessor]

[server]
labels = {  }
addr="0.0.0.0:20160"
advertise-addr="tikv-gateway0:20160"

[storage]
data-dir="./data/tikv0/" 

[pd]
# This section will be overwritten by command line parameters	
endpoints=["pd0:2379"]

[metric]
#address = "172.16.30.31:9531"
#interval = "15s"
#job = "tikv"

[raftstore]
raftdb-path = ""
sync-log = true
consistency-check-interval = "10s"
raft-log-gc-count-limit = 256

[coprocessor]
region-max-keys = 144000
region-split-keys = 96000
region-max-size = "144MB"
region-split-size = "96MB"

[rocksdb]
wal-dir = ""
max-open-files = 1000

[rocksdb.defaultcf]
block-cache-size = "10GB"

[rocksdb.lockcf]
block-cache-size = "4GB"

[rocksdb.writecf]
block-cache-size = "4GB"

[raftdb]
max-open-files = 1000

[raftdb.defaultcf]
block-cache-size = "1GB"

[security]
ca-path = ""
cert-path = ""
key-path = ""

[import]
