FROM hub.pingcap.net/tiflash/tikv-learner:190508

ARG ENGINE_ADDR="172.17.0.1"

RUN echo "Engine address is: ${ENGINE_ADDR}"
COPY ./config/tikv-learner.toml /tikv.toml
RUN sed -i "s/ENGINE_ADDR/${ENGINE_ADDR}/" /tikv.toml
